Add tests back

diff --git a/bin/download b/bin/download
--- a/bin/download
+++ b/bin/download
@@ -7,7 +7,7 @@ plugin_dir=$(dirname "$(dirname "$current_script_path")")
 
 # shellcheck source=./lib/utils.bash
 . "${plugin_dir}/lib/utils.bash"
-detect_plugin_name
+detect_tool_name
 
 main() {
 	local install_type="$1"
@@ -16,10 +16,10 @@ main() {
 	if [ "$install_type" != "version" ]; then
 		fail "only release installs are supported, got: $install_type"
 	fi
-	printf "Downloading %s version %s to %s\n" "$PLUGIN_NAME" "$version" "$download_path"
-	if ! python3 -m pip download -q "$PLUGIN_NAME"=="$version" --disable-pip-version-check \
-		--only-binary "$PLUGIN_NAME" --dest "$download_path"; then
-		fail "could not download $PLUGIN_NAME version $version"
+	printf "Downloading %s version %s to %s\n" "$TARGET_TOOL_NAME" "$version" "$download_path"
+	if ! python3 -m pip download -q "$TARGET_TOOL_NAME"=="$version" --disable-pip-version-check \
+		--only-binary "$TARGET_TOOL_NAME" --dest "$download_path"; then
+		fail "could not download $TARGET_TOOL_NAME version $version"
 	fi
 	printf "Downloaded:\n"
 	find "${download_path}/" | xargs printf "  %s\n" || true
diff --git a/bin/latest-stable b/bin/latest-stable
--- a/bin/latest-stable
+++ b/bin/latest-stable
@@ -7,7 +7,7 @@ plugin_dir=$(dirname "$(dirname "$current_script_path")")
 
 # shellcheck source=./lib/utils.bash
 . "${plugin_dir}/lib/utils.bash"
-detect_plugin_name
+detect_tool_name
 
 py_get_latest() {
 	cat <<EOF
@@ -24,6 +24,6 @@ else:
 EOF
 }
 
-if ! python3 -m pip index --json versions "$PLUGIN_NAME" | python3 -c "$(py_get_latest)" "${1:-}"; then
-	fail "Failed to get latest version for plugin '$PLUGIN_NAME'."
+if ! python3 -m pip index --json versions "$TARGET_TOOL_NAME" | python3 -c "$(py_get_latest)" "${1:-}"; then
+	fail "Failed to get latest version for plugin '$TARGET_TOOL_NAME'."
 fi
diff --git a/bin/list-all b/bin/list-all
--- a/bin/list-all
+++ b/bin/list-all
@@ -7,7 +7,7 @@ plugin_dir=$(dirname "$(dirname "$current_script_path")")
 
 # shellcheck source=./lib/utils.bash
 . "${plugin_dir}/lib/utils.bash"
-detect_plugin_name
+detect_tool_name
 
 py_list_versions() {
 	cat <<EOF
@@ -18,6 +18,6 @@ for version in reversed(q['versions']):
 EOF
 }
 
-if ! python3 -m pip index --json versions "$PLUGIN_NAME" | python3 -c "$(py_list_versions)"; then
-	fail "Failed to list versions for plugin '$PLUGIN_NAME'."
+if ! python3 -m pip index --json versions "$TARGET_TOOL_NAME" | python3 -c "$(py_list_versions)"; then
+	fail "Failed to list versions for plugin '$TARGET_TOOL_NAME'."
 fi
