Import changes

diff --git a/bin/download b/bin/download
--- a/bin/download
+++ b/bin/download
@@ -8,16 +8,16 @@ plugin_dir=$(dirname "$(dirname "$current_script_path")")
 # shellcheck source=./lib/utils.bash
 source "${plugin_dir}/lib/utils.bash"
 
-mkdir -p "$ASDF_DOWNLOAD_PATH"
+main() {
+	local install_type="$1"
+	local version="$2"
+	local download_path="${3}"
+	if [ "$install_type" != "version" ]; then
+		fail "asdf-clang-format supports release installs only"
+	fi
+	if ! python3 -m pip download clang-format=="$version" --no-deps --only-binary clang-format --dest "$download_path"; then
+		fail "could not download clang-format version $version"
+	fi
+}
 
-# TODO: Adapt this to proper extension and adapt extracting strategy.
-release_file="$ASDF_DOWNLOAD_PATH/$TOOL_NAME-$ASDF_INSTALL_VERSION.tar.gz"
-
-# Download tar.gz file to the download directory
-download_release "$ASDF_INSTALL_VERSION" "$release_file"
-
-#  Extract contents of tar.gz file into the download directory
-tar -xzf "$release_file" -C "$ASDF_DOWNLOAD_PATH" --strip-components=1 || fail "Could not extract $release_file"
-
-# Remove the tar.gz file since we don't need to keep it
-rm "$release_file"
+main "$ASDF_INSTALL_TYPE" "$ASDF_INSTALL_VERSION" "$ASDF_DOWNLOAD_PATH"
diff --git a/bin/install b/bin/install
--- a/bin/install
+++ b/bin/install
@@ -8,4 +8,35 @@ plugin_dir=$(dirname "$(dirname "$current_script_path")")
 # shellcheck source=./lib/utils.bash
 source "${plugin_dir}/lib/utils.bash"
 
-install_version "$ASDF_INSTALL_TYPE" "$ASDF_INSTALL_VERSION" "$ASDF_INSTALL_PATH"
+main() {
+	local install_type="$1"
+	local version="$2"
+	local install_path="${3%/bin}"
+	local download_path="$4"
+	local wheel
+
+	if [ "$install_type" != "version" ]; then
+		fail "asdf-clang-format supports release installs only"
+	fi
+
+	(
+		wheel="$(find "$download_path" -maxdepth 1 -type f -name "clang_format-${version}*.whl" | head -n 1)"
+		if [ -z "$wheel" ]; then
+			fail "No wheel file found for version $version in $download_path"
+		fi
+		mkdir -p "${install_path}/bin"
+		python3 -m venv "${install_path}/venv"
+		# shellcheck disable=SC1091
+		. "${install_path}/venv/bin/activate"
+		python3 -m pip install --no-index --no-deps "$wheel"
+		local tool="${install_path}/venv/bin/clang-format"
+		local tool_link="${install_path}/bin/clang-format"
+		ln -s "$tool" "$tool_link"
+		[ -x "$tool_link" ] || fail "Expected $tool_link to be executable."
+	) || (
+		rm -rf "$install_path"
+		fail "An error occurred while installing clang-format $version."
+	)
+}
+
+main "$ASDF_INSTALL_TYPE" "$ASDF_INSTALL_VERSION" "$ASDF_INSTALL_PATH" "$ASDF_DOWNLOAD_PATH"
