Better message

diff --git a/bin/post-plugin-add b/bin/post-plugin-add
--- a/bin/post-plugin-add
+++ b/bin/post-plugin-add
@@ -17,3 +17,11 @@ printf "Detected plugin root:\n"
 printf "        %s\n" "${PLUGIN_ROOT}"
 printf "Detected target tool name:\n"
 printf "        %s\n" "${TARGET_TOOL_NAME}"
+printf "\n"
+printf "Checking PyPI for availability of %s...\n" "${TARGET_TOOL_NAME}"
+if ! python3 -m pip index versions "${TARGET_TOOL_NAME}"; then
+    printf "Failed to find %s on PyPI.\n" "${TARGET_TOOL_NAME}"
+    printf "Check that the plugin name chosen matches the PyPI package name\n"
+    printf "and that the package exists on pypi.org.\n"
+    exit 1
+fi
